# Generated by Django 5.0.4 on 2024-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_alter_vendor_on_time_delivery_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fullfillment_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
